todo/urls.py
from django.urls import path

from todo.views import (
    # index,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskListView, TaskUpdateView, TaskDeleteView, complete_undo_button,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("create-task/", TaskCreateView.as_view(), name="task-create"),
    path("update-task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("delete-task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),

    path("change-is-done/<int:pk>/complete-undo/", complete_undo_button, name="complete-undo")

]


app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ['-is_done', '-created_at']

    def __str__(self):
        return self.content

todo/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import DateTimeInput

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )
    deadline = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
    )

    class Meta:
        model = Task
        fields = ['content', 'deadline', 'tags']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Tag, Task


# def index(request):
#     tags = Tag.objects.all()
#
#     context = {
#         "tags": tags,
#     }
#
#     return render(request, "todo/index.html", context=context)


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "todo/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")
    template_name = "todo/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


def complete_undo_button(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect("todo:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

{#      {% block pagination %}#}
{#        {% include "includes/pagination.html" %}#}
{#      {% endblock %}#}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO List
    <a style="float: right" href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">Add Task</a>
  </h1>
  <div>
    {% for task in task_list %}
      <hr>
      <p><strong>Content:</strong> {{ task.content }}</p>
      <p><strong>Created:</strong> {{ task.created_at }}</p>
      <p><strong>Tags:</strong> {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}</p>
        {% if task.is_done %}
    <form method="POST" action="{% url 'todo:complete-undo' pk=task.pk %}" class="ml-auto">
        {% csrf_token %}
        <button type="submit" class="btn btn-sm btn-secondary float-right ml-2">Undo</button>
    </form>
{% else %}
    <form method="POST" action="{% url 'todo:complete-undo' pk=task.pk %}" class="ml-auto">
        {% csrf_token %}
        <button type="submit" class="btn btn-sm btn-success float-right ml-2">Complete</button>
    </form>
{% endif %}
      <a class="btn btn-sm btn-outline-primary" href="{% url 'todo:task-update' pk=task.id %}">
          Update
      </a>
      <a class="btn btn-sm btn-outline-danger" href="{% url 'todo:task-delete' pk=task.id %}">
          Delete
      </a>
    {% empty %}
      <p>No task!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a style="float: right" href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>


  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary link-to-page">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo:tag-delete' pk=tag.id %}"class="btn btn-secondary link-to-page">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in todo-list.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}